name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*"
      - "snapshot-*"
      - "tptlibsdev-*"
  pull_request:
    branches:
      - "*"

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      do_release: ${{ steps.prepare.outputs.do_release }}
      build_matrix: ${{ steps.prepare.outputs.build_matrix }}
      release_type: ${{ steps.prepare.outputs.release_type }}
      release_name: ${{ steps.prepare.outputs.release_name }}
      mod_id: ${{ steps.prepare.outputs.mod_id }}
      app_name: ${{ steps.prepare.outputs.app_name }}
      app_comment: ${{ steps.prepare.outputs.app_comment }}
      app_exe: ${{ steps.prepare.outputs.app_exe }}
      app_id: ${{ steps.prepare.outputs.app_id }}
      app_data: ${{ steps.prepare.outputs.app_data }}
      app_vendor: ${{ steps.prepare.outputs.app_vendor }}

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python -m pip install meson ninja

      - id: prepare
        run: python ./.github/prepare.py
        env:
          GITHUB_REF: ${{ github.ref }}

      - if: steps.prepare.outputs.do_release == 'yes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.prepare.outputs.release_name }}
        run: bash ./.github/create-release.sh

  build:
    runs-on: ${{ matrix.runs_on }}
    name: ${{ matrix.job_name }}
    needs: prepare

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.build_matrix) }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - if: matrix.runs_on == 'ubuntu-22.04-arm'
        run: |
          for var in HOME PATH XDG_CONFIG_HOME; do
            sed -Ee "s/^/${var}=/" -e 's/(runner)admin/\1/g' <<< "${!var}"
          done | tee -a "$GITHUB_ENV"

      - if: matrix.force_msys2_bash == 'yes'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msys2_msystem }}
          update: true
          path-type: strict
          cache: true
          install: ${{ matrix.msys2_cache_install }}

      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

      - if: matrix.force_msys2_bash != 'yes'
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - if: matrix.force_msys2_bash != 'yes'
        run: python -m pip install meson ninja

      - if: matrix.bsh_build_platform == 'darwin'
        run: brew install bash coreutils

      - run: bash ./.github/build.sh
        env:
          BSH_HOST_ARCH: ${{ matrix.bsh_host_arch }}
          BSH_HOST_PLATFORM: ${{ matrix.bsh_host_platform }}
          BSH_HOST_LIBC: ${{ matrix.bsh_host_libc }}
          BSH_STATIC_DYNAMIC: ${{ matrix.bsh_static_dynamic }}
          BSH_BUILD_PLATFORM: ${{ matrix.bsh_build_platform }}
          BSH_DEBUG_RELEASE: ${{ matrix.bsh_debug_release }}
          BSH_LINT: ${{ matrix.bsh_lint }}
          RELEASE_NAME: ${{ needs.prepare.outputs.release_name }}
          RELEASE_TYPE: ${{ needs.prepare.outputs.release_type }}
          MOD_ID: ${{ needs.prepare.outputs.mod_id }}
          APP_NAME: ${{ needs.prepare.outputs.app_name }}
          APP_COMMENT: ${{ needs.prepare.outputs.app_comment }}
          APP_EXE: ${{ needs.prepare.outputs.app_exe }}
          APP_ID: ${{ needs.prepare.outputs.app_id }}
          APP_DATA: ${{ needs.prepare.outputs.app_data }}
          APP_VENDOR: ${{ needs.prepare.outputs.app_vendor }}
          SEPARATE_DEBUG: ${{ matrix.separate_debug }}
          PACKAGE_MODE: ${{ matrix.package_mode }}
          ASSET_PATH: ${{ matrix.asset_path }}
          DEBUG_ASSET_PATH: ${{ matrix.debug_asset_path }}

      # ===== 普通产物 =====
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job_name }}__${{ matrix.asset_name }}
          path: build/${{ matrix.asset_path }}

      # ===== Debug 产物 =====
      - if: matrix.separate_debug == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job_name }}__${{ matrix.debug_asset_name }}
          path: build/${{ matrix.debug_asset_path }}

  release_upload:
    runs-on: ubuntu-24.04
    needs: [prepare, build]
    if: needs.prepare.outputs.do_release == 'yes'

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: |
          sudo apt update
          sudo apt install -y gh

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          shopt -s nullglob
          for f in artifacts/*/*; do
            gh release upload "$GITHUB_REF_NAME" "$f" --clobber
          done
